# Generated by Django 3.0.3 on 2020-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
