# Generated by Django 3.1 on 2020-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_board_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.AddField(
            model_name='article',
            name='file_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
